import {readFile,writeFile,mkdir} from 'node:fs/promises';import {join} from 'node:path';import sharp from 'sharp';import {REPO_ROOT} from '../paths.mjs';
const root=join(REPO_ROOT,'storage/products/003/prompt-05-review'),manifest=JSON.parse(await readFile(join(root,'page-format-manifest.json'),'utf8'));
await mkdir(join(root,'contact-sheets'),{recursive:true});await mkdir(join(root,'inspection'),{recursive:true});
const pages=manifest.jobs.flatMap(j=>j.pages.map(p=>({...j,page:p.page,path:join(root,p.pngPath)})));
async function sheet(items,path,{cols=4,width=3200,cellH=1150}={}){const rows=Math.ceil(items.length/cols),cellW=Math.floor(width/cols),composite=[];for(let i=0;i<items.length;i++){const x=(i%cols)*cellW,y=Math.floor(i/cols)*cellH,label=`${items[i].name} · p${String(items[i].page).padStart(2,'0')}`;const img=await sharp(items[i].path).resize({width:cellW-36,height:cellH-80,fit:'contain',background:'#2a2428'}).toBuffer();composite.push({input:img,left:x+18,top:y+42});const svg=Buffer.from(`<svg width="${cellW}" height="42"><rect width="100%" height="100%" fill="#171316"/><text x="16" y="27" fill="#f3e8d6" font-family="Arial" font-size="18">${label}</text></svg>`);composite.push({input:svg,left:x,top:y});}await sharp({create:{width,height:rows*cellH,channels:3,background:'#2a2428'}}).composite(composite).jpeg({quality:90}).toFile(path);}
for(const theme of ['full-colour','economy']){const selected=pages.filter(p=>p.theme===theme&&p.format==='A4');for(let i=0;i<selected.length;i+=28)await sheet(selected.slice(i,i+28),join(root,'contact-sheets',`${theme}-${String(i/28+1).padStart(2,'0')}.jpg`),{cols:4,width:3200,cellH:1080});}
for(let i=0;i<pages.length;i+=4)await sheet(pages.slice(i,i+4),join(root,'inspection',`inspection-${String(i/4+1).padStart(2,'0')}.jpg`),{cols:4,width:4000,cellH:1480});
const select=names=>names.map(n=>pages.find(p=>p.name===n&&p.page===1));
await sheet(select(['G01-full-colour-A4','G02-full-colour-A4','G03-full-colour-A4','G04-full-colour-A4','G05-full-colour-A4','G06-full-colour-A4','G11-full-colour-A4','G16-full-colour-A4']),join(root,'contact-sheets','player-host-answer-comparison.jpg'),{cols:4,width:3600,cellH:1250});
await sheet(select(['G12-full-colour-A4','G12-full-colour-US-Letter','G13-full-colour-A4','G13-full-colour-US-Letter']),join(root,'contact-sheets','cutting-sheet-comparison.jpg'),{cols:4,width:4000,cellH:1500});
const bingo=pages.filter(p=>p.id==='G07'&&p.theme==='full-colour'&&p.format==='A4');await sheet(bingo,join(root,'contact-sheets','all-bingo-boards.jpg'),{cols:4,width:3600,cellH:1250});
await sheet(bingo.slice(2,5),join(root,'contact-sheets','bingo-03-04-05-comparison.jpg'),{cols:3,width:3600,cellH:1700});
await writeFile(join(root,'review-index.json'),JSON.stringify({status:'CONTACT_SHEETS_READY',pageCount:pages.length,inspectionSheets:Math.ceil(pages.length/4),contactSheets:['full-colour-01.jpg','full-colour-02.jpg','economy-01.jpg','economy-02.jpg','all-bingo-boards.jpg','cutting-sheet-comparison.jpg','player-host-answer-comparison.jpg']},null,2));console.log(`Prepared ${pages.length} pages in ${Math.ceil(pages.length/4)} inspection sheets`);
