import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
import { contained, PRODUCT_ROOT, outputPath } from '../paths.mjs';
export async function buildEditor(resources) {
  const bundled=await build({entryPoints:[contained(PRODUCT_ROOT,'src/edit/editor.mjs')],bundle:true,write:false,format:'iife',platform:'browser'});
  const resourceData={tokens:resources.tokens,schemas:resources.schemas,defaults:resources.defaults,fonts:resources.fonts,artwork:resources.artwork};
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Midnight Séance — offline proof editor</title><style>
  ${resources.fonts}*{box-sizing:border-box}body{margin:0;background:#F4EBDD;color:#171315;font:15px 'Source Sans 3',sans-serif}header{padding:24px 32px;border-bottom:1px solid #A98A5B}h1{font:32px 'Bodoni Moda';margin:0 0 8px}header p{margin:4px 0}main{display:grid;grid-template-columns:360px 1fr;gap:24px;padding:24px}aside{padding:20px;border:1px solid #A98A5B;background:white}label{display:block;margin:0 0 12px;font-weight:600}textarea,select{display:block;width:100%;font:15px 'Source Sans 3';margin:5px 0;padding:8px;border:1px solid #6A5A49;border-radius:0}small{font-weight:400;color:#342434}button,.load-label{font:15px 'Source Sans 3';padding:9px 14px;border:1px solid #701F2A;background:white;color:#701F2A;cursor:pointer;margin:4px 0}button:disabled{opacity:.45;cursor:default}#status{padding:12px 0}#status[data-state=error]{color:#701F2A}iframe{width:840px;height:1160px;border:0;background:white;transform-origin:top left}#preview-wrap{overflow:auto;max-width:100%}.notice{font-size:14px;line-height:1.5}.load-label input{display:block;margin-top:8px}
  </style></head><body><header><h1>Midnight Séance</h1><p>Text-only offline editor · Prompt 3 artwork proof</p><p class="notice">Original illustrated artwork proof for visual approval. This is a review proof, not the final customer collection.</p></header><main><aside><label>Page<select id="kind"><option value="invitation">Invitation</option><option value="welcome">Welcome sign</option></select></label><label>Treatment<select id="theme"><option value="full-colour">Signature Ivory</option><option value="economy">Economy White</option></select></label><label>Paper<select id="size"><option>5x7</option><option>a4</option><option>us-letter</option></select></label><div id="fields"></div><div id="status" role="status"></div><button id="print" disabled>Print / Save PDF</button> <button id="reset">Reset text</button> <button id="save">Save text file</button><label class="load-label">Load saved text<input id="load" type="file" accept="application/json,.json"></label><p class="notice">Open locally in desktop Chrome or Edge. In Print: choose the selected paper size, scale 100%, margins None, headers/footers Off. Turn Background graphics On for Signature Ivory. Native invitation: use 5 × 7 in custom paper or select A4/Letter here and trim the centered card. No account, connection or font installation required.</p><p class="notice">Latin-script text and ordinary punctuation supported. Over-limit, unsupported and visibly overlapping text blocks printing. No text is silently truncated.</p></aside><div id="preview-wrap"><iframe id="preview" title="Print preview"></iframe></div></main><script>window.MIDNIGHT_RESOURCES=${JSON.stringify(resourceData).replace(/</g,'\\u003c')};</script><script>${bundled.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')}</script></body></html>`;
  const path=outputPath('editable','midnight-seance-proof-editor.html');await writeFile(path,html);return path;
}
