export function stationeryStyles(){return `
.placement{position:absolute}.placement>.design{width:100%;height:100%}.cut-guides{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.cut-guides line{stroke:#777;stroke-width:.12}.cut-guides .fold{stroke-dasharray:1 .7}.print-sheet-label{position:absolute;left:10mm;bottom:3mm;color:#333;font-size:8.5pt}.stationery{--hero-w:32mm;--hero-h:36mm}
.collection-line{font-size:9pt;text-transform:uppercase;letter-spacing:.16em;color:var(--secondary);text-align:center;line-height:1.35}.formal-top-left,.formal-bottom-right{position:absolute;width:23mm;height:32mm}.formal-top-left{left:4mm;top:4mm}.formal-bottom-right{right:4mm;bottom:4mm}
.formal-content{position:absolute;inset:12mm 15mm;display:flex;flex-direction:column;align-items:stretch;justify-content:space-between;gap:2mm;text-align:center}.stationery-hero{height:var(--hero-h);display:flex;justify-content:center;align-items:center;flex-shrink:0}.hero-art{width:var(--hero-w);height:var(--hero-h)}.stationery-closing{display:flex;justify-content:center;align-items:center;flex-shrink:0;height:14mm}.closing-art{width:55mm;height:14mm}.formal-title{font-family:'Bodoni Moda';font-size:24pt;line-height:1.2;color:var(--accent)}.utility-label{font-size:8.5pt;line-height:1.4;letter-spacing:.08em;text-transform:uppercase;font-weight:600;color:var(--secondary)}.detail-block{display:flex;flex-direction:column;gap:1mm}.body-copy{font-size:10.5pt}.utility-copy{font-size:8.5pt;line-height:1.4}.formal-moon-phases{width:55mm;height:9mm;margin:0 auto;flex-shrink:0}
.details-content{inset:12mm 14mm;gap:1.5mm}.master-S02{--hero-w:14mm;--hero-h:24mm}.master-S02 .formal-title{font-size:21pt}.master-S02 .closing-art{width:18mm;height:13mm}.master-S02 .stationery-closing{height:13mm}
.sign-content{position:absolute;inset:17mm 30mm 20mm;display:flex;flex-direction:column;align-items:stretch;justify-content:space-between;gap:4mm;text-align:center}.sign-title{font-family:'Bodoni Moda';font-size:48pt;line-height:1.12;text-transform:uppercase;color:var(--accent)}.sign-subtitle{font-size:14pt;letter-spacing:.05em;text-transform:uppercase;line-height:1.3}.sign-message{font-size:17pt;line-height:1.45}.sign-footer{display:flex;flex-direction:column;gap:3mm}.sign-phrase{font-family:'Bodoni Moda';font-style:italic;font-size:17pt;line-height:1.4}.sign-botanical-left,.sign-botanical-right{position:absolute;bottom:5mm;width:35mm;height:50mm}.sign-botanical-left{left:5mm}.sign-botanical-right{right:5mm}.archetype-sign{--hero-w:36mm;--hero-h:48mm}.archetype-sign .stationery-closing{height:18mm}.archetype-sign .closing-art{width:70mm;height:18mm}.master-S04{--hero-w:24mm;--hero-h:42mm}.master-S06{--hero-w:26mm;--hero-h:38mm}.master-S07{--hero-w:20mm;--hero-h:42mm}.master-S08{--hero-w:28mm;--hero-h:28mm}
.compact-title{font-family:'Bodoni Moda';text-transform:uppercase;font-size:32pt;line-height:1.18;color:var(--accent)}.formal-subtitle{font-size:12pt;line-height:1.35;letter-spacing:.03em}.formal-detail{font-family:'Bodoni Moda';font-size:16pt;line-height:1.4}.master-S09{--hero-w:55mm;--hero-h:30mm}.master-S10{--hero-w:25mm;--hero-h:35mm}
.menu-content{inset:11mm 16mm;gap:1.8mm}.master-S11{--hero-w:18mm;--hero-h:20mm}.course{display:flex;flex-direction:column;gap:1mm;padding-top:2mm;border-top:.6pt solid var(--ornament)}.course-name{font-family:'Bodoni Moda';font-size:14pt;line-height:1.3}.course-detail{font-size:10pt;line-height:1.35;font-style:italic}.master-S11 .stationery-closing,.master-S12 .stationery-closing{height:13mm}.master-S11 .closing-art,.master-S12 .closing-art{width:18mm;height:13mm}
.drinks-content{inset:11mm 16mm;gap:1.5mm}.master-S12{--hero-w:14mm;--hero-h:25mm}.drink-list{display:flex;flex-direction:column;gap:2.2mm}.drink-name{font-family:'Bodoni Moda';font-size:13pt;color:var(--accent);line-height:1.25}.drink-detail{font-size:9pt;line-height:1.35}.drink-entry{display:flex;flex-direction:column;gap:.4mm}
.small-frame{position:absolute;inset:3mm;border:.6pt solid var(--ornament);pointer-events:none}.small-frame:before{content:'';position:absolute;inset:1mm;border:.6pt solid var(--accent)}.small-star{width:5mm;height:5mm;margin:0 auto;flex-shrink:0}.small-leaf-divider{width:30mm;height:8mm;margin:0 auto;flex-shrink:0}.place-card-content{position:absolute;inset:6mm;display:flex;flex-direction:column;justify-content:space-between;align-items:stretch;gap:2mm}.guest-name{font-family:'Bodoni Moda';font-size:17pt;line-height:1.3;color:var(--accent)}
.tent-front{position:absolute;left:0;right:0;bottom:0;height:50.8mm;background:var(--paper)}.tent-back{position:absolute;inset:0 0 50.8mm;background:white;display:flex;align-items:center;justify-content:center}.tent-back .small-star{transform:rotate(180deg)}.food-card-content{position:absolute;inset:6mm;display:flex;flex-direction:column;justify-content:space-between;gap:1.2mm}.food-name{font-family:'Bodoni Moda';font-size:15pt;line-height:1.3;color:var(--accent)}.food-note{font-size:8.5pt;line-height:1.3}
.potion-content{position:absolute;inset:6mm;display:flex;gap:3mm;align-items:center}.potion-bottle{width:18mm;height:35mm;flex-shrink:0}.potion-copy{display:flex;flex-direction:column;gap:2mm;flex:1;min-width:0}.potion-copy .utility-label{font-size:8.5pt;letter-spacing:0}.potion-name{font-family:'Bodoni Moda';font-size:14pt;line-height:1.2;color:var(--accent)}.potion-detail{font-size:8.5pt;line-height:1.3}
.tag-content{position:absolute;inset:12mm 6mm 6mm;display:flex;flex-direction:column;justify-content:space-between;align-items:stretch;gap:2mm}.master-S16{--hero-w:18mm;--hero-h:18mm}.tag-message{font-family:'Bodoni Moda';font-size:15pt;line-height:1.2;color:var(--accent)}.tag-host{font-size:9pt;line-height:1.3}.master-S16 .closing-art{width:18mm;height:13mm}.master-S16 .stationery-closing{height:13mm}
.guestbook-content{position:absolute;inset:13mm 16mm;display:flex;flex-direction:column;gap:4mm}.guestbook-botanical{position:absolute;top:6mm;right:6mm;width:20mm;height:22mm}.guestbook-title{font-family:'Bodoni Moda';font-size:30pt;line-height:1.3;color:var(--accent)}.guestbook-prompt{font-size:12pt;line-height:1.4}.writing-lines{flex:1;display:flex;flex-direction:column;justify-content:space-evenly;min-height:100mm}.writing-lines>div{border-bottom:.6pt solid var(--ornament);height:10mm}.guestbook-name{display:flex;align-items:center;gap:3mm;margin-top:4mm}.name-label{font-size:11pt;white-space:nowrap}.guestbook-name>span{border-bottom:.6pt solid var(--ornament);flex:1;height:6mm}.guestbook-content .closing-art{width:18mm;height:13mm}
.master-S18{--hero-w:20mm;--hero-h:20mm}.thanks-title{font-family:'Bodoni Moda';text-transform:uppercase;font-size:29pt;color:var(--accent);line-height:1.2}.thanks-content{inset:13mm 15mm}.thanks-message{font-family:'Bodoni Moda';font-size:15pt;line-height:1.4}.thanks-signoff{font-size:10pt;line-height:1.35}.master-S18 .closing-art{width:55mm;height:14mm}
.sheet.economy .small-frame:before{display:none}
/* Bodoni's ascenders and descenders need the same generous leading as the approved proofs. */
.sign-title{font-size:44pt;line-height:1.3}.formal-title,.compact-title,.tag-message,.thanks-title{line-height:1.3}.potion-name{line-height:1.35}
.master-S12{--hero-w:16mm;--hero-h:28mm}
.slim-potion-content{position:absolute;inset:6mm;display:flex;flex-direction:column;align-items:stretch;justify-content:space-between;gap:1mm}.horizontal-bottle{height:13mm;width:52mm;position:relative;margin:0 auto;flex-shrink:0}.slim-potion-bottle{position:absolute;width:13mm;height:52mm;left:19.5mm;top:-19.5mm}.slim-potion-bottle img{transform:rotate(90deg)}
.thanks-message{font-size:13pt}.thanks-title.long{font-size:22pt}.master-S18:has(.thanks-title.long){--hero-w:18mm;--hero-h:18mm}.master-S18:has(.thanks-title.long) .stationery-closing,.master-S18:has(.thanks-title.long) .closing-art{height:10mm}
`;}
