import { field, heading, grid, escapeText } from '../components/index.mjs';
import {illustratedFrame} from '../components/artwork.mjs';
export function invitation(values,art) {
  return `<article class="design invitation" data-master="S01">${illustratedFrame('invitation',art)}${art('A01','botanic-tl','invitation-botanical-top-left')}${art('A02','botanic-tr','invitation-botanical-top-right')}${art('A03','botanic-bl','invitation-botanical-bottom-left')}${art('A04','botanic-br','invitation-botanical-bottom-right')}<div class="invitation-content"><div class="summons">${heading('You are','Summoned')}</div><div class="invitation-hero">${art('B01','hero-moth','invitation-hero')}${art('C02','moon-phases','invitation-moon-phases')}</div>${field('eventTitle',values.eventTitle,'event-title')}${art('E04','engraved-separator','invitation-event-divider')}<div class="date-group">${field('date',values.date,'date')}${field('time',values.time,'time')}</div><div class="venue-group">${field('venue',values.venue,'venue')}${field('address',values.address,'address')}</div>${field('host',values.host,'host')}<div class="invitation-footer">${field('rsvp',values.rsvp,'rsvp')}${field('dressCode',values.dressCode,'dress-code')}</div></div></article>`;
}
export function welcome(values,size,art) {
  return `<article class="design welcome size-${size}" data-master="S03">${illustratedFrame('welcome',art)}${art('A03','welcome-botanic-left','welcome-botanical-bottom-left')}${art('A04','welcome-botanic-right','welcome-botanical-bottom-right')}<div class="welcome-content"><div class="celestial-hero">${art('C01','crescent','welcome-upper-celestial')}${art('C04','celestial-stars left','welcome-upper-stars-left')}${art('C04','celestial-stars right','welcome-upper-stars-right')}</div><div class="welcome-greeting">${heading('Welcome','To the')}</div>${field('eventTitle',values.eventTitle,'event-title')}${art('E04','engraved-separator','welcome-title-divider')}${field('host',values.host,'host')}${art('B02','raven-pair','welcome-raven-focal')}<div class="welcome-closing">${field('subtitle',values.subtitle,'subtitle')}${field('motto',values.motto,'motto')}</div><div class="welcome-seal">${art('A05','botanical-divider','welcome-lower-botanical-arrangement')}</div></div></article>`;
}
export function wordSearch(spec,puzzle,answer,art) {
  return `<article class="design activity" data-master="${answer?'G04':'G03'}">${illustratedFrame('activity',art)}${art('A06','activity-botanic','word-search-header-ornament')}<div class="activity-top"><span class="kicker">Midnight Séance · ${answer?'Host copy':'Parlour games'}</span>${art('C02','moon-phases','activity-moon-phases')}</div>${heading(answer?'The hidden words, revealed':'A little mystery for curious minds',answer?'The answer lies within':spec.title)}<p class="instructions">${escapeText(answer?spec.answerInstructions:spec.instructions)}</p>${grid(puzzle,answer)}<div class="word-list">${spec.words.map(w=>`<div class="word"><span class="check-box"></span>${w}</div>`).join('')}</div><div class="activity-footer-motif">${art('E05','footer-emblem','activity-footer-motif')}</div><footer class="activity-footer">${answer?'Keep this page with the host.':'Good company. Strange questions. Darker revelations.'}</footer></article>`;
}
