export function styles(tokens,fonts,theme,size,kind) {
  const t=tokens.themes[theme], [w,h]=tokens.sizes[size];
  if(!t||!w)throw new Error('Unknown theme or size');
  return `${fonts}
  :root{--paper:${t.paper};--ink:${t.text};--accent:${t.accent};--secondary:${t.secondary};--ornament:${t.ornament};--rule:${t.rule}}
  *{box-sizing:border-box}html,body{margin:0;padding:0}body{color:var(--ink);font-family:'Source Sans 3',Arial,sans-serif;font-size:10pt;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  @page{size:${w}mm ${h}mm;margin:0}.sheet{width:${w}mm;height:${h}mm;position:relative;background:white;display:flex;align-items:center;justify-content:center;break-after:page;overflow:hidden}.sheet:last-child{break-after:auto}
  .design{position:relative;background:var(--paper);color:var(--ink);flex-shrink:0}.invitation{width:127mm;height:177.8mm}.welcome{width:203.2mm;height:254mm}.welcome.size-a4{width:190mm;height:277mm}.welcome.size-us-letter{width:195.9mm;height:259.4mm}.activity{width:${w-20}mm;height:${h-20}mm;padding:9mm 10mm}
  h1,.event-title{font-family:'Bodoni Moda',Georgia,serif;font-weight:400;font-optical-sizing:none;font-variation-settings:'opsz' 18,'wght' 400}h1{margin:0;text-transform:uppercase;line-height:1.02}.kicker{font-size:8.5pt;text-transform:uppercase;letter-spacing:.16em;font-weight:600;color:var(--secondary)}
  .frame{position:absolute;inset:6mm;border:.6pt solid var(--rule);pointer-events:none}.frame:before{content:'';position:absolute;inset:1.7mm;border:.6pt solid var(--ornament);border-radius:8mm 0 8mm 0}.corner{position:absolute;width:5.5mm;height:5.5mm;color:var(--accent);background:var(--paper);padding:1mm}.tl{left:-2.75mm;top:-2.75mm}.tr{right:-2.75mm;top:-2.75mm}.bl{left:-2.75mm;bottom:-2.75mm}.br{right:-2.75mm;bottom:-2.75mm}.frame-bead{position:absolute;left:calc(50% - .8mm);width:1.6mm;height:1.6mm;border:.6pt solid var(--ornament);background:var(--paper);transform:rotate(45deg)}.frame-bead.top{top:-.8mm}.frame-bead.bottom{bottom:-.8mm}
  .star{display:block;width:100%;height:100%}.moon-phases{display:block;width:30mm;height:5.2mm;color:var(--accent);margin:auto}.crescent{display:block;width:30mm;height:30mm;color:var(--ornament);margin:0 auto}.divider{display:flex;align-items:center;justify-content:center;gap:3mm;height:5mm;color:var(--accent)}.divider span{height:0;width:15mm;border-top:.6pt solid var(--ornament)}.divider>.star{width:3mm;height:3mm}
  .field{white-space:pre-wrap;overflow-wrap:anywhere;text-align:center;line-height:1.25}.invitation-content{position:absolute;inset:14mm 14mm 13mm;display:flex;flex-direction:column;align-items:stretch;justify-content:space-between;text-align:center;gap:1.5mm}.summons h1{font-size:29pt;letter-spacing:.025em}.summons .kicker{font-family:'Bodoni Moda';font-size:13pt;letter-spacing:.12em;margin-bottom:1.5mm;color:var(--ink);font-weight:400}.summons{flex-shrink:0}.invitation .moon-phases{flex-shrink:0}
  .invitation .event-title{font-size:26pt;line-height:1.02;text-transform:uppercase;color:var(--accent);max-height:30mm}.invitation .event-title.long{font-size:20pt}.date-group{display:flex;flex-direction:column;gap:1mm}.date{font-size:10pt;font-weight:600}.time{font-size:9.5pt}.venue-group{display:flex;flex-direction:column;gap:1mm}.venue{font-size:10pt;font-weight:600}.address{font-size:9pt}.host{font-size:9pt;letter-spacing:.025em}.invitation .host:before{content:'Hosted by ';font-style:italic}.invitation-footer{display:flex;flex-direction:column;gap:2mm}.rsvp{font-size:8.5pt}.dress-code{font-family:'Bodoni Moda';font-style:italic;font-size:10pt;color:var(--secondary)}
  .welcome-content{position:absolute;inset:22mm 23mm 18mm;display:flex;flex-direction:column;align-items:center;justify-content:space-between;text-align:center;gap:4mm}.welcome-greeting .kicker{font-family:'Bodoni Moda';font-weight:400;color:var(--ink);font-size:24pt;letter-spacing:.075em}.welcome-greeting h1{font-size:14pt;margin-top:2mm;letter-spacing:.2em}.welcome .event-title{font-size:56pt;line-height:1.06;color:var(--accent);text-transform:uppercase;max-width:100%}.welcome .event-title.long{font-size:38pt}.welcome .host{font-size:12pt;text-transform:uppercase;letter-spacing:.1em}.welcome .host.long{font-size:10pt}.welcome-closing{display:flex;flex-direction:column;gap:3mm;max-width:100%}.welcome .subtitle{font-size:11pt;text-transform:uppercase;letter-spacing:.09em}.welcome .motto{font-family:'Bodoni Moda';font-style:italic;font-size:15pt;line-height:1.3;color:var(--secondary)}.welcome-seal .moon-phases{width:34mm;height:6mm}
  .activity-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:5mm}.activity-top .moon-phases{margin:0;width:24mm;height:4mm}.activity h1{font-size:26pt;line-height:1.05;color:var(--accent);text-transform:none;margin-top:2mm}.activity .kicker{font-size:8.5pt;letter-spacing:.12em}.instructions{font-size:10pt;line-height:1.4;margin:4mm 0 5mm;max-width:160mm}.activity-grid{display:grid;grid-template-columns:repeat(16,8.2mm);width:131.2mm;height:131.2mm;margin:0 auto;border:.6pt solid var(--ornament)}.cell{display:flex;align-items:center;justify-content:center;width:8.2mm;height:8.2mm;font-size:12pt;line-height:1;font-weight:600;border-right:.3pt solid #C9BBA6;border-bottom:.3pt solid #C9BBA6}.cell.solution{background:${theme==='economy'?'#E6E6E6':'#E6CDD0'};color:var(--ink);text-decoration:underline;text-decoration-thickness:.6pt;text-underline-offset:1pt}.word-list{display:grid;grid-template-columns:repeat(3,1fr);column-gap:4mm;row-gap:2mm;max-width:144mm;margin:5mm auto 3mm}.word{font-size:9pt;display:flex;align-items:center;gap:2mm;letter-spacing:.035em}.check-box{width:2.5mm;height:2.5mm;border:.6pt solid var(--secondary);display:inline-block}.activity-footer{text-align:center;font-family:'Bodoni Moda';font-style:italic;font-size:11pt;margin-top:2mm}.activity>.divider{height:4mm}
  h1{line-height:1.25}.invitation .moon-phases{margin:2mm auto}.invitation .event-title{width:80mm;align-self:center;line-height:1.3}.invitation .event-title.long{width:96mm}.welcome .event-title{line-height:1.3}.welcome .motto{line-height:1.4}
  ${theme==='economy'?'.frame:before{border:none}.frame{border-color:var(--rule)}.cell{border-color:#D5D5D5}':''}
  /* Prompt 2 revision: engraved development ornaments, never final artwork. */
  .frame{inset:5mm;border:.6pt solid var(--ornament)}.frame:before{inset:2mm;border:1pt solid var(--accent);border-radius:0}.frame:after{content:'';position:absolute;inset:3.4mm;border:.6pt solid var(--ornament);pointer-events:none}.corner{width:7mm;height:7mm;padding:1.3mm}.tl,.bl{left:-3.5mm}.tr,.br{right:-3.5mm}.tl,.tr{top:-3.5mm}.bl,.br{bottom:-3.5mm}.frame-break{position:absolute;top:47%;width:4mm;height:10mm;padding:2mm .5mm;background:var(--paper);color:var(--accent)}.frame-break.left{left:-2mm}.frame-break.right{right:-2mm}
  .artwork-slot{pointer-events:none;color:var(--accent)}.development-motif{display:block;width:100%;height:100%}.engraving{stroke-width:.65}.botanic-tl,.botanic-tr,.botanic-bl,.botanic-br{position:absolute;width:12mm;height:29mm;z-index:1}.botanic-tl{left:8mm;top:8mm}.botanic-tr{right:8mm;top:8mm;transform:scaleX(-1)}.botanic-bl{left:8mm;bottom:8mm;transform:scaleY(-1)}.botanic-br{right:8mm;bottom:8mm;transform:scale(-1)}
  .invitation-content{inset:13mm 14mm 12mm;gap:1mm}.summons h1{color:var(--accent);font-size:31pt;letter-spacing:.045em}.summons .kicker{font-size:12pt}.invitation-hero{position:relative;flex-shrink:0;height:17mm;display:flex;align-items:center;justify-content:center}.hero-moth{width:18mm;height:12mm;position:absolute;left:calc(50% - 9mm);top:0}.invitation-hero .moon-phases{width:67mm;height:5mm;margin:0;background:var(--paper)}.hero-moth+.moon-phases{position:absolute;bottom:0;top:auto}.invitation .event-title{font-size:28pt}.invitation .event-title.long{font-size:20pt}.date{font-size:10.5pt}.time,.venue{font-size:10pt}.address,.host{font-size:9.5pt}.rsvp{font-size:9pt}.dress-code{font-size:10.5pt}.invitation-footer{gap:1.5mm}.invitation .divider{border-top:.6pt solid var(--ornament);border-bottom:.6pt solid var(--ornament);height:5mm;flex-shrink:0}
  .welcome-content{inset:18mm 23mm 20mm;gap:3mm}.celestial-hero{width:64mm;height:38mm;flex-shrink:0;position:relative;border-bottom:.6pt solid var(--ornament)}.celestial-hero:before,.celestial-hero:after{content:'';position:absolute;color:var(--accent);width:3mm;height:3mm;border:.6pt solid var(--accent);transform:rotate(45deg);top:10mm}.celestial-hero:before{left:3mm}.celestial-hero:after{right:3mm}.celestial-hero .crescent{width:35mm;height:35mm}.welcome .event-title{font-size:60pt;line-height:1.2}.welcome .event-title.long{font-size:38pt}.welcome-greeting .kicker{font-size:26pt}.welcome .host{font-size:12pt}.welcome-closing{padding:5mm 0 3mm;border-top:.6pt solid var(--ornament);width:100%;gap:2mm}.welcome .motto{font-size:16pt}.welcome-seal{width:70mm;height:13mm;display:flex;justify-content:center;align-items:center;border-top:.6pt solid var(--ornament);border-bottom:.6pt solid var(--ornament)}.welcome-botanic-left,.welcome-botanic-right{position:absolute;bottom:9mm;width:17mm;height:60mm}.welcome-botanic-left{left:8mm;transform:scaleY(-1)}.welcome-botanic-right{right:8mm;transform:scale(-1)}
  .frame-activity{inset:3mm;border-color:var(--ornament)}.frame-activity:before{inset:1.3mm;border-width:.6pt;border-radius:0}.frame-activity:after,.frame-activity .frame-break{display:none}.frame-activity .corner{width:4mm;height:4mm;padding:.7mm}.frame-activity .tl,.frame-activity .bl{left:-2mm}.frame-activity .tr,.frame-activity .br{right:-2mm}.frame-activity .tl,.frame-activity .tr{top:-2mm}.frame-activity .bl,.frame-activity .br{bottom:-2mm}.activity-botanic{position:absolute;right:6mm;top:7mm;width:11mm;height:22mm}.activity-top{margin-bottom:3mm;padding-bottom:2mm;border-bottom:.6pt solid var(--ornament)}.activity-top .moon-phases{margin-right:9mm}.activity h1{font-size:28pt}.activity>header{border-left:1.5pt solid var(--accent);padding-left:3mm}.instructions{margin:3mm 0 4mm;font-size:10.5pt}.activity-grid{outline:.8pt solid var(--accent);outline-offset:1.2mm}.word-list{border-top:.6pt solid var(--ornament);border-bottom:.6pt solid var(--ornament);padding:3mm 0;row-gap:1.7mm;margin:4mm auto 2mm}.word{font-size:9.5pt}.activity-footer-motif .divider{height:3mm}.activity-footer{font-size:11pt;margin-top:1mm;color:var(--secondary)}
  ${theme==='economy'?'.frame:before{border:.6pt solid var(--rule)}.frame:after{display:none}.artwork-slot{color:var(--ink)}.summons h1{color:var(--ink)}.activity-grid{outline-color:var(--rule)}':''}
  .invitation-hero{height:22mm}.hero-moth{height:18mm;width:30mm;left:calc(50% - 15mm)}.welcome-botanic-left,.welcome-botanic-right{width:14mm}.celestial-hero{width:78mm;height:42mm}.celestial-hero .crescent{width:39mm;height:39mm}
  .invitation:has(.event-title.long) .summons h1{font-size:27pt}.invitation:has(.event-title.long) .invitation-hero{height:10mm}.invitation:has(.event-title.long) .hero-moth{height:7mm;width:15mm;left:calc(50% - 7.5mm)}.invitation:has(.event-title.long) .invitation-hero .moon-phases{height:3mm;width:54mm}.invitation:has(.event-title.long) .botanic-bl,.invitation:has(.event-title.long) .botanic-br{width:6mm}
  /* Prompt 3: original RGBA engravings; all artwork keeps its native aspect. */
  .artwork-slot img{display:block;width:100%;height:100%;object-fit:contain;object-position:center}
  .frame-star{width:100%;height:100%}.frame-activity .corner{width:5mm;height:5mm;padding:.6mm}
  .botanic-tl,.botanic-tr,.botanic-bl,.botanic-br{width:28mm;height:32mm;transform:none}
  .botanic-tl{left:4.5mm;top:4.5mm}.botanic-tr{right:4.5mm;top:4.5mm}
  .botanic-bl{left:4.5mm;bottom:4.5mm}.botanic-br{right:4.5mm;bottom:4.5mm}
  .invitation-hero{height:30mm}.hero-moth{width:38mm;height:22mm;left:calc(50% - 19mm)}
  .invitation-hero .moon-phases{position:absolute;bottom:0;width:55mm;height:8mm;left:calc(50% - 27.5mm);background:none}
  .engraved-separator{width:55mm;height:4mm;align-self:center;flex-shrink:0;margin:0 auto}
  .invitation:has(.event-title.long) .botanic-bl,.invitation:has(.event-title.long) .botanic-br{width:16mm;height:20mm}
  .invitation:has(.event-title.long) .hero-moth{width:20mm;height:10mm;left:calc(50% - 10mm)}
  .invitation:has(.event-title.long) .invitation-hero{height:15mm}
  .invitation:has(.event-title.long) .invitation-hero .moon-phases{width:45mm;height:5mm;left:calc(50% - 22.5mm)}
  .celestial-hero:before,.celestial-hero:after{display:none}.celestial-hero{border:0}
  .celestial-hero .crescent{width:32mm;height:35mm}.celestial-stars{position:absolute;top:8mm;width:14mm;height:18mm}
  .celestial-stars.left{left:3mm}.celestial-stars.right{right:3mm}
  .welcome-botanic-left,.welcome-botanic-right{width:35mm;height:50mm;bottom:5mm;transform:none}
  .welcome-botanic-left{left:5mm}.welcome-botanic-right{right:5mm}
  .raven-pair{width:55mm;height:26mm;flex-shrink:0}.welcome-seal{width:70mm;height:18mm;border:0;flex-shrink:0}
  .botanical-divider{width:70mm;height:18mm}.welcome-closing{padding:3mm 0 2mm}
  .welcome:has(.event-title.long) .celestial-hero{height:30mm}.welcome:has(.event-title.long) .crescent{height:28mm}
  .welcome:has(.event-title.long) .raven-pair{height:20mm;width:36mm}
  .welcome:has(.event-title.long) .welcome-seal,.welcome:has(.event-title.long) .botanical-divider{height:12mm;width:55mm}
  .activity-botanic{width:17mm;height:20mm;top:6mm;right:6mm}.activity-top .moon-phases{margin-right:15mm;width:30mm;height:5mm}
  .activity-footer-motif{height:13mm;margin-top:1mm;display:flex;justify-content:center}.footer-emblem{width:18mm;height:13mm}
  @media print{html,body{width:${w}mm}.sheet{box-shadow:none}}`;
}
